// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('createCollaborativeMap', function() {
  jest.setTimeout(90000);
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('createCollaborativeMap', async function() {
    await driver.get("http://localhost:8081/")
    await driver.manage().window().setRect({ width: 1936, height: 1066 })
    
    // Click on register button first
    await driver.findElement(By.css(".r-backgroundColor-slr29l")).click()
    
    // Wait for the registration form to load
    await driver.wait(until.elementLocated(By.css(".input-container:nth-child(1) input")), 5000);
    
    await driver.findElement(By.css(".input-container:nth-child(1) input")).click()
    await driver.findElement(By.css(".input-container:nth-child(1) input")).sendKeys("Pepe")
    await driver.findElement(By.css(".input-container:nth-child(2) input")).sendKeys("viyuela")
    await driver.findElement(By.css(".input-container:nth-child(3) input")).sendKeys("pepeviyuelaa")
    await driver.findElement(By.css(".input-container:nth-child(5) input")).click()
    await driver.findElement(By.css(".input-container:nth-child(5) input")).sendKeys("pepesviyuela@mail.com")
    await driver.findElement(By.css(".input-container:nth-child(6) input")).click()
    await driver.findElement(By.css(".input-container:nth-child(6) input")).sendKeys("Contraseña55$")
    await driver.findElement(By.css(".terms-link")).click()
    
    await driver.wait(until.elementLocated(By.css(".sc-jbAkgO")), 5000);
    
    // Handle terms and conditions scroll
    const slaContainer = await driver.findElement(By.css(".sc-jbAkgO"));
    await driver.executeScript("arguments[0].scrollTop = arguments[0].scrollHeight", slaContainer);
    await driver.sleep(1000);
    
    await driver.findElement(By.css(".sc-cSaEAk")).click()
    await driver.findElement(By.css("button:nth-child(8)")).click()
    
    // Wait for next page to load after registration
    await driver.wait(until.elementLocated(By.css("button:nth-child(3)")), 5000);
    
    // Use JavaScript click to avoid ElementClickInterceptedError
    const continueButton = await driver.findElement(By.css("button:nth-child(3)"));
    await driver.executeScript("arguments[0].click();", continueButton);
    
    // Wait a moment for navigation to complete
    await driver.sleep(2000);
    
    // Rest of the test remains the same
    try {
      await driver.findElement(By.css(".css-view-175oi2r:nth-child(2) > .r-transitionProperty-1i6wzkk > .css-text-146c3p1")).click();
    } catch (e) {
      // If direct click fails, try JavaScript click
      const menuButton = await driver.findElement(By.css(".css-view-175oi2r:nth-child(2) > .r-transitionProperty-1i6wzkk > .css-text-146c3p1"));
      await driver.executeScript("arguments[0].click();", menuButton);
    }
    
    await driver.sleep(1000);
    
    try {
      await driver.findElement(By.css(".css-view-175oi2r:nth-child(6) > .css-text-146c3p1")).click();
    } catch (e) {
      const mapButton = await driver.findElement(By.css(".css-view-175oi2r:nth-child(6) > .css-text-146c3p1"));
      await driver.executeScript("arguments[0].click();", mapButton);
    }
    
    await driver.sleep(1000);
    
    try {
      await driver.findElement(By.css(".r-borderRadius-1h84pjw > .css-text-146c3p1")).click();
    } catch (e) {
      const createButton = await driver.findElement(By.css(".r-borderRadius-1h84pjw > .css-text-146c3p1"));
      await driver.executeScript("arguments[0].click();", createButton);
    }
    
    await driver.sleep(1000);
    
    try {
      await driver.findElement(By.css(".r-marginInline-8dgmk1 > .r-color-jwli3a")).click();
    } catch (e) {
      const premiumButton = await driver.findElement(By.css(".r-marginInline-8dgmk1 > .r-color-jwli3a"));
      await driver.executeScript("arguments[0].click();", premiumButton);
    }
    
    await driver.sleep(1000);
    
    // Handle iframe for payment
    await driver.switchTo().frame(1)
    await driver.findElement(By.name("cardnumber")).click()
    await driver.findElement(By.name("cardnumber")).sendKeys("4242 4242 4242 4242")
    await driver.findElement(By.name("exp-date")).sendKeys("07 / 30")
    await driver.findElement(By.name("cvc")).sendKeys("345")
    await driver.switchTo().defaultContent()
    
    try {
      await driver.findElement(By.css("form > button")).click();
    } catch (e) {
      const payButton = await driver.findElement(By.css("form > button"));
      await driver.executeScript("arguments[0].click();", payButton);
    }
    
    await driver.sleep(3000);
    
    // The rest of navigation with JavaScript click fallbacks
    try {
      await driver.findElement(By.css(".r-backgroundColor-1afzr4o > .css-text-146c3p1")).click();
    } catch (e) {
      const menuButtonAgain = await driver.findElement(By.css(".r-backgroundColor-1afzr4o > .css-text-146c3p1"));
      await driver.executeScript("arguments[0].click();", menuButtonAgain);
    }
    
    await driver.sleep(1000);
    
    try {
      await driver.findElement(By.css(".css-view-175oi2r:nth-child(2) > .r-transitionProperty-1i6wzkk > .css-text-146c3p1")).click();
    } catch (e) {
      const menuItemButton = await driver.findElement(By.css(".css-view-175oi2r:nth-child(2) > .r-transitionProperty-1i6wzkk > .css-text-146c3p1"));
      await driver.executeScript("arguments[0].click();", menuItemButton);
    }
    
    await driver.sleep(1000);
    
    try {
      await driver.findElement(By.css(".css-view-175oi2r:nth-child(6) > .css-text-146c3p1")).click();
    } catch (e) {
      const mapButton = await driver.findElement(By.css(".css-view-175oi2r:nth-child(6) > .css-text-146c3p1"));
      await driver.executeScript("arguments[0].click();", mapButton);
    }
    
    await driver.sleep(1000);
    
    try {
      await driver.findElement(By.css(".r-borderRadius-1h84pjw > .css-text-146c3p1")).click();
    } catch (e) {
      const createButton = await driver.findElement(By.css(".r-borderRadius-1h84pjw > .css-text-146c3p1"));
      await driver.executeScript("arguments[0].click();", createButton);
    }
    
    // Fill in map details
    await driver.findElement(By.css(".css-textinput-11aywtz:nth-child(3)")).sendKeys("Lipton de limon")
    await driver.findElement(By.css(".r-minHeight-mjyw6")).sendKeys("Los chavale lpgc ")
    
    try {
      await driver.findElement(By.css(".css-view-175oi2r:nth-child(2) > .r-color-djgu52")).click();
    } catch (e) {
      const optionButton = await driver.findElement(By.css(".css-view-175oi2r:nth-child(2) > .r-color-djgu52"));
      await driver.executeScript("arguments[0].click();", optionButton);
    }
    
    try {
      await driver.findElement(By.css(".r-marginInline-8dgmk1 > .r-color-jwli3a")).click();
    } catch (e) {
      const submitButton = await driver.findElement(By.css(".r-marginInline-8dgmk1 > .r-color-jwli3a"));
      await driver.executeScript("arguments[0].click();", submitButton);
    }
    
    await driver.sleep(2000);
    
    try {
      await driver.findElement(By.css(".r-transitionProperty-1i6wzkk > .r-flex-13awgt0")).click();
    } catch (e) {
      const finalButton = await driver.findElement(By.css(".r-transitionProperty-1i6wzkk > .r-flex-13awgt0"));
      await driver.executeScript("arguments[0].click();", finalButton);
    }
  })
})