// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  jest.setTimeout(30000);
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    await driver.get("http://localhost:8081/")
    await driver.manage().window().setRect({ width: 1936, height: 1066 })
    await driver.findElement(By.css(".r-borderColor-1wr2p1e > .css-text-146c3p1")).click()
    await driver.findElement(By.css(".input-container:nth-child(1) input")).click()
    await driver.findElement(By.css(".input-container:nth-child(1) input")).sendKeys("user1@gmail.com")
    await driver.findElement(By.css(".input-container:nth-child(2) input")).sendKeys("user12345*")
    await driver.findElement(By.css("div:nth-child(3) > button")).click()
  })
})
