// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('register', function() {
  jest.setTimeout(60000); // Updated to 60 seconds
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('register', async function() {
    await driver.get("http://localhost:8081/")
    await driver.manage().window().setRect({ width: 1936, height: 1066 })
    await driver.findElement(By.css(".r-backgroundColor-slr29l")).click()
    await driver.findElement(By.css(".input-container:nth-child(1) input")).click()
    await driver.findElement(By.css(".input-container:nth-child(1) input")).sendKeys("tony")
    await driver.findElement(By.css(".input-container:nth-child(2) input")).sendKeys("montana")
    await driver.findElement(By.css(".input-container:nth-child(3) input")).sendKeys("tonymontana")
    await driver.findElement(By.css(".input-container:nth-child(5) input")).click()
    await driver.findElement(By.css(".input-container:nth-child(5) input")).sendKeys("tony@montana.com")
    await driver.findElement(By.css(".input-container:nth-child(6) input")).click()
    await driver.findElement(By.css(".input-container:nth-child(6) input")).sendKeys("Pepe4$55")
    await driver.findElement(By.css(".terms-link")).click()
    await driver.wait(until.elementLocated(By.css(".sc-jbAkgO")), 5000);
    const slaContainer = await driver.findElement(By.css(".sc-jbAkgO"));
    await driver.executeScript("arguments[0].scrollTop = arguments[0].scrollHeight", slaContainer);
    await slaContainer.sendKeys(Key.END);
    await driver.sleep(1000);
    await driver.findElement(By.css(".sc-cSaEAk")).click()
    await driver.findElement(By.css("button:nth-child(8)")).click()
  })
})