# Este archivo est치 comentado para evitar su ejecuci칩n
# Para usar este archivo, elimina los comentarios y ejecute `docker-compose -f docker-compose-frontend.yml up -d`

# version: '3.8'

# services:
#   # Frontend Web
#   frontend-web:
#     build:
#       context: ../..
#       dockerfile: infrastructure/docker/Dockerfile.web
#     container_name: mapyourworld-web
#     restart: unless-stopped
#     environment:
#       NODE_ENV: production
#       REACT_APP_API_URL: ${API_URL:-http://localhost:3000}
#       REACT_APP_WS_URL: ${WS_URL:-ws://localhost:3000}
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - web_build:/app/build
#       - ./nginx/ssl:/etc/nginx/ssl
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

#   # Servicios de desarrollo
#   web-dev:
#     image: node:18-alpine
#     container_name: mapyourworld-web-dev
#     command: sh -c "cd /app && npm install && npm run dev"
#     volumes:
#       - ../../frontend/web:/app
#     ports:
#       - "3006:3000"
#     environment:
#       NODE_ENV: development
#       REACT_APP_API_URL: ${API_DEV_URL:-http://localhost:3000}
#       REACT_APP_WS_URL: ${WS_DEV_URL:-ws://localhost:3000}
#     profiles:
#       - dev

#   # Servicio de compilaci칩n m칩vil
#   mobile-builder:
#     image: node:18
#     container_name: mapyourworld-mobile-builder
#     command: sh -c "cd /app && npm install && npm run build"
#     volumes:
#       - ../../frontend/mobile:/app
#       - mobile_build:/app/build
#     environment:
#       NODE_ENV: production
#       EXPO_API_URL: ${API_URL:-http://localhost:3000}
#       EXPO_WS_URL: ${WS_URL:-ws://localhost:3000}
#     profiles:
#       - mobile-build

# volumes:
#   web_build:
#   mobile_build: 