name: Test Workflow 2
on:
  push:
    branches:
      - 'feature/CI-CD'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test workflow NUMBER 2"
      - run: echo "Current branch is ${{ github.ref }}"