name: Test Workflow
on:
  push:
    branches:
      - '*'  # Run on all branches

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test workflow NUMBER 2"
      - run: echo "Current branch is ${{ github.ref }}"